### ISSUE TITLE
Add pca10040/s140 support

### ISSUE THREAD

**Issue by talyssoncastro** [kaidyth/nrf52_bootloader#19]
I'm totally new to this world, this question might be easy to answer.
Is there a way (and of course, how can I do it) to add the support to board pca10040?

**Comment by charlesportwoodii** [comment]
This bootloader only supports nRF52840 chips. PCA10040 is nRF52832. There's some architectural differences between the two.

I recommend looking at the Adafruit bootloader if you want a similar set of features for 2832.

**Comment by charlesportwoodii** [comment]
Take a look at https://github.com/kaidyth/nrf52_bootloader/issues/12.

Might be worth reaching out to see if they can share/upstream their additions if the Adafruit bl isn't appealing
